# Generated by Django 5.0.3 on 2024-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(max_length=11)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
    ]
