# Generated by Django 5.0.3 on 2024-03-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='details',
        ),
    ]
