# Generated by Django 5.0.3 on 2024-03-31 11:53

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi')], default='bangla', max_length=100),
        ),
    ]
